### ISSUE TITLE
Some variables are not defined

### ISSUE THREAD

**Issue by stonecropa** [ValentinKoch/SVDNA#2]
@ValentinKoch 
This code has some issues and bugs. Here are some issues and bugs I found:

You should define the function before calling the svdna function, because the interpreter needs to know the definition of the function before calling the function. Move the definition of the svdna function before the call.

In the get_all_statistics function, you used the get_random_images function to get random target images. However, the definition of the get_random_images function is not provided in the code. Make sure the definition of the function exists and returns the correct random image path.

In the svdna function, you resized the image and used the np.reshape function to resize the dimensions. However, the dimensionally adjusted results may not be what you expect. Check the resizing code to make sure the resizing shape is what you expect.

In the final drawing part, you used some undefined variables, such as resized_cirrus, resized_topcon, resized_bioptigen, svdna_im_cirrus, svdna_im_topcon and svdna_im_bioptigen. Make sure these variables are defined before plotting and contain the correct image data.

In the final drawing part, you used ax5.axis("off") to turn off the axis of the fifth subplot. However, ax5 is not defined in the previous code. Make sure you define these undefined variables before using them.

**Comment by ValentinKoch** [comment]
Hi, 
thanks for using the repository and your valuable feedback! I moved all the function definitions to the beginning as you suggested :) 
The function "get_random_images" is defined as far as I can see, if not here is the implementation I used: 
```
def get_random_images(path,length=1):
    all_images = sorted(Path(path).glob("*.png"))
    return np.random.choice(all_images, length,replace=False)
```

The resizing function is doing what I expect it to do, could you please let me know what kind of issues you are facing? 

I will update it so that you can see how the images you are referring to were generated! 
Unfortunately I cant provide you with the images themselves, but at least the Farsiu dataset is publicly available.

If you need any more assistance please let me know ;) 

Best
Valentin
