### ISSUE TITLE
How to make a noisy image less noisy

### ISSUE THREAD

**Issue by stonecropa** [ValentinKoch/SVDNA#5]
@ValentinKoch 
Thank you for your previous excellent answer. 
Now i have a question how to reduce the noise of this image to be like the second image.How to do it specifically, should I use cyclegan?Sorry, I didn't find Figure 4 in your paper. Showing your supplementary data in springer's database is missing.I would appreciate it if you could reply me.
![image](https://github.com/ValentinKoch/SVDNA/assets/114655828/e62d3e5d-f873-4cc7-87e0-faeefee7e2e4)

**Comment by ValentinKoch** [comment]
Hi,

thanks for reaching out again :) 
Denoising is way harder than adding noise, in my opinion a basic cycle GAN is not ideal as it can introduce artifacts and especially in out of distribution samples can completely fail. Here the figure you were refering to: 
![gancomp3](https://github.com/ValentinKoch/SVDNA/assets/55893735/f9af8794-ce76-49cc-b7a0-09b0c89927b3)
_Note the distorted brightness of tissue in the second and third image compared to overall good translation in the first example._
It depends on what your final goal is, if it is classification or segmentation you might not even need to denoise. My first try would always be histogram matching for these kind of tasks. If you really want to make it less noisy you could maybe try more recent cycleGAN like architectures, id maybe give this a try: https://arxiv.org/abs/1905.01270 
Also, I found out that a decent amount of noise can be also removed by a simple one-liner, which however can sometimes delete also minor details: 
image<np.average(image)=0 will remove a lot of the speckle noise but is obviously a bit hacky ;) 

Best 
Valentin

**Comment by stonecropa** [comment]
@ValentinKoch 
First of all thanks for the great answer, yes I am doing segmentation task but there is really too much noise in the picture and also you can see how bad my dataset images are. And my oct image is divided into ten layers. If the invalid area is added, it will be the eleventh floor. If images are not preprocessed effectively, it may result in low training accuracy or long training time.
Also, is the code you mentioned something like this ？
import numpy as np
Import image from PIL

# Read a grayscale image and convert it to a NumPy array
gray_image = np.array(Image.open('output.png').convert('L'))

# Compute the average of the image
average_value = np.average(grayscale image)

# set the threshold
threshold = mean

# Set the pixels less than the threshold in the image to 0, and keep the pixels greater than or equal to the threshold
processed_gray_image = np.where(gray_image < threshold, 0, gray_image)

# Convert NumPy array back to grayscale image and save
processed_gray_image = Image.fromarray(processed_gray_image.astype(np.uint8), mode='L')
processed_gray_image.save('aouputvvvv2.png')

Here are my before and after pictures
![output](https://github.com/ValentinKoch/SVDNA/assets/114655828/64d75808-0a41-495b-8217-7ca1406516be)
![aouputvvvv2](https://github.com/ValentinKoch/SVDNA/assets/114655828/b327f73a-ac34-44b3-ae52-8fedc96245c8)
Looking forward to your reply, sincerely

**Comment by ValentinKoch** [comment]
Hi, 
yes the code sample you provided was what I meant! For me this reduced (validation) loss and looked optically a bit better, the segmentation performance was however only very slightly better so not sure if its a good idea overall. Im not sure how you plot and save the images, one thing that is important if you use matplotlib.pyplot.imshow is to set vmin=0 and vmax=255 so that you can actually compare two images, if you dont do this it will automatically infer these values which can lead to unwanted optical effects in the sense that the same value of a pixel will look different across different images. Maybe not relevant but it took me a while to figure out so I thought I might share :)
"If the invalid area is added, it will be the eleventh floor." I do not exactly get what you mean by this, could you please elaborate? 
Thanks! 👍 
Also i found this nice collection of image to image translation papers if you want to try cycleGAN like architectures: https://github.com/weihaox/awesome-image-translation 
Best
Valentin

**Comment by stonecropa** [comment]
@ValentinKoch 
Thank you for your reply, I will study the code you recommend carefully
I'm sorry that I didn't explain clearly at the beginning, but when I marked it, I divided the following layers
0 Background background (non-retina effective area)
1 ILM (or NFL upper line)
2 NFL - GCL dividing line
3 GCL - IPL dividing line
4 IPL - INL dividing line
5 INL - OPL dividing line
6 OPL - ONL dividing line
7 ELM wires
8 IS/OS lines
9 RPE line (the dividing line with choroid)
10 choroid lower boundary line

**Comment by ValentinKoch** [comment]
Thanks for your clarification! I will close this issue, feel free to open a new one if anything comes up.
